### ISSUE TITLE
Transaction is aborted if AuthenticationPolicy to access the database

### ISSUE THREAD

**Issue by yosida95** [Pylons/pyramid_tm#13]
If unauthorized_userid method of authentication policy to need to access the database, two or more transaction is started during handling one request and first transaction is aborted because `pyramid.security.unauthenticated_usreid` is called out of transaction manager in a method which returned value of `pyramid_tm.tm_tween_factory` (https://github.com/Pylons/pyramid_tm/blob/master/pyramid_tm/__init__.py#L50)

**Comment by pacahon** [comment]
Have the same problem with header-based authentication policy. I'm using sqlalchemy and after read-only transaction is aborted, my session select query unbound from sqlalchemy Session.
Is it save if unauthenticated_userid method will return header auth token instead of user id?

**Comment by timka** [comment]
No, it‘s not. Token serves other purpose than user id and has completely different lifecycle. If you technically use token to identify a user you end up in a situation when the user has different id every time, but the sole purpose of id is being constant.

**Comment by tseaver** [comment]
I'm afraid we won't "fix" this usage in `pyramid_tm`.  If you have the usecase (accessing the database "outside" the scope of the transaction managed by `pyramid_tm`, then you need to handle that access yourself.
