### ISSUE TITLE
pyramid_tm will not roll back transactions on custom pyramid exception handlers

### ISSUE THREAD

**Issue by GevatterGaul** [Pylons/pyramid_tm#16]
Hi,

using Pyramid 1.5.1 and pyramid_tm 0.7 and waitress 0.8.9, pyramid_tm will not roll back a transaction when a HTTPNotFound Exception is handled via a custom exception handler. This is the handler code:

	class ErrorHandling(BaseLayout):
		def __init__(self, context, request):
			self.context = context
			self.request = request

		@view_config(
			context=HTTPNotFound,
			renderer='project:templates/static/404.mak'
		)
		def notfound(self):
			self.request.response.status_code = 404
			return dict()

This can result in a database lock that stays active until it receives a timeout, therefore blocking all other operations on the same row.

Interestingly, a transaction.abort() in the handler code will not help either. Is there a possible fix with pyramid_tm?

**Comment by GevatterGaul** [comment]
We use sqlalchemy, zope.sqlalchemy and mysql-connector-python. I can try to reproduce the issue if it helps?

**Comment by mmerickel** [comment]
I'm fairly certain so far that you have a bug or misunderstanding in how you're handling your database connections, given the proposed bug as well as saying `transaction.abort()` is not working either. This tells me things just aren't setup properly in your app. Feel free to paste some code or try to reproduce the issue though.

**Comment by GevatterGaul** [comment]
Ok, maybe we can address a possible misunderstanding first: I was under the impression, that when an exception is raised in a view, pyramid_tm will call `transaction.abort()`, which in turn will cause zope.sqlalchemy that is hooked into the transaction mechanism to rollback the current database transaction. Pyramid then passes the exception to the custom exception handler.
Is that correct?

**Comment by mmerickel** [comment]
This is all true, with the (very improbable in this case) assumption that zope.sqlalchemy is hooked into your session. I say this because both exceptions and `transaction.abort()` do exactly the same thing in pyramid_tm's point of view (it calls `transaction.abort()` itself).

**Comment by mmerickel** [comment]
Please reopen this issue if you have a more concrete example of what's happening but so far it seems like things are working as expected and that there is a misconfiguration in your app.
