### ISSUE TITLE
setUser() and note() is necessary or not?

### ISSUE THREAD

**Issue by theking-laptop** [Pylons/pyramid_tm#29]
I read source code and I know `pyramid_tm` use two methods `setUser` and `note`. I read `transaction` API too and I think it's not very important. But actually, I'm not familiar with them so I can't affirm that. I decide to ask author of this repo :)

Do they make `transaction` do its work correctly (join-active-transaction-per-userid, thread safety, etc...)? Or just for debugging, logging? Do they impact performance? In Pyramid application, don't use them, I mean `.user` attribute is always empty string for every request, everything is okay?

Okay, if my guess (they are not very important) is correct, should you let user decide to use them or not via options?

Thanks!

**Comment by tseaver** [comment]
Those two methods set per-transaction metadata:  an app could choose to display them (e.g., Zope's [undo view](http://docs.zope.org/zope2/zope2book/UsingZope.html#transactions-and-undoing-mistakes)).  They are not required.
