### ISSUE TITLE
Add a Hook To Customize the TransactionManager instace

### ISSUE THREAD

**Issue by dstufft** [Pylons/pyramid_tm#30]
Currently ``pyramid_tm`` more or less requires using the same transaction manager for every request, which more or less means that it *must* be the thread local transaction manager if the application needs to be thread safe. It would be great if a ``manager_hook` could be added which was a callable which was passed the ``request`` and is expected to return the transaction manager for this particular request. This would enable applications to use explicit transaction managers instead of relying on a thread local one.

The patch itself should be fairly simply, here's a small diff that does what I'd like (lacking tests and documentation though):
```diff
diff --git a/pyramid_tm/__init__.py b/pyramid_tm/__init__.py
index 937cecc..34f1409 100644
--- a/pyramid_tm/__init__.py
+++ b/pyramid_tm/__init__.py
@@ -35,9 +35,11 @@ def tm_tween_factory(handler, registry, transaction=transaction):
     old_commit_veto = registry.settings.get('pyramid_tm.commit_veto', None)
     commit_veto = registry.settings.get('tm.commit_veto', old_commit_veto)
     activate = registry.settings.get('tm.activate_hook')
+    manager_hook = registry.settings.get('tm.manager_hook')
     attempts = int(registry.settings.get('tm.attempts', 1))
     commit_veto = resolver.maybe_resolve(commit_veto) if commit_veto else None
     activate = resolver.maybe_resolve(activate) if activate else None
+    manager_hook = resolver.maybe_resolve(manager_hook) if manager_hook else None
     assert attempts > 0
 
     def tm_tween(request):
@@ -49,7 +51,11 @@ def tm_tween_factory(handler, registry, transaction=transaction):
             if not activate(request):
                 return handler(request)
 
-        manager = transaction.manager
+        if manager_hook is not None:
+            manager = manager_hook(request)
+        else:
+            manager = transaction.manager
+
         number = attempts
         if hasattr(request, 'unauthenticated_userid'):
             userid = request.unauthenticated_userid

```

**Comment by mmerickel** [comment]
Yes, +1. This is something that @inklesspen and I had touched on a couple weeks ago and this looks like a great way to do it. I would also advocate in both scenarios attaching a `request.tm` request property which applications could use to get a reference to whichever tm was active.

**Comment by bertjwregeer** [comment]
From IRC:

> 21:17:21 < dstufft> Ah, inklesspen. just a FYI, in https://metaclassical.com/what-the-zope-transaction-manager-means-to-me-and-you/ you mentioned "The transaction manager is still provided as a threadlocal under this design; I'm 
                    working on a way to fix that.", well it bothered me to have thar thead local so I sorted out a way of doing it (though it requires a small patch to pyramid_tm).
> 21:17:23 < dstufft> inklesspen: https://bpaste.net/show/5a6e4d915f62 + The patch in https://github.com/Pylons/pyramid_tm/issues/30 == success, for whatever it's worth.
> 21:19:18 < dstufft> inklesspen: oh forgot this too, https://bpaste.net/show/86dd14042cbd to register the created session with zope.sqlalchemy (though you probably could have sorted it out)

**Comment by dstufft** [comment]
Ah, yea I was doing that in my own code, but it would probably make sense to do it right here in pyramid_tm.

**Comment by dstufft** [comment]
I went ahead and added a pull request that solves there at #31. I went a little bit different but not much.
