### ISSUE TITLE
Online docs missing

### ISSUE THREAD

**Issue by dz0ny** [Pylons/pyramid_tm#38]
http://docs.pylonsproject.org/projects/pyramid-tm/en/latest/

**Comment by stevepiercy** [comment]
@dz0ny thanks for the report. I confirm.

I tried to force a build through https://readthedocs.org/projects/pyramid_tm/builds/ but it didn't work. @mmerickel or @mcdonc are the two Owners at RTD https://readthedocs.org/projects/pyramid_tm/ so hopefully one of them can sort it out, or add me as an Owner so I can poke it with a stick.

I was able to build the docs locally, FWIW.

**Comment by mmerickel** [comment]
docs seem to be working now.
