### ISSUE TITLE
support using the transaction inside exception views

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_tm#40]
A major short-coming in the current implementation is that the transaction has already been committed or aborted by the time an exception view is executed since the tween lies UNDER the EXCVIEW.

This can cause weird errors in your app because you may have transactional items attached to the request and thus the references are still around in the exception view. Also it'd often times nice to be able to continue doing queries, etc even if the changes will later be aborted.

The most common scenario can be solved by having `zope.sqlalchemy` avoid expiring objects on flush, but this doesn't solve the issue of performing more queries in the exception views. It just allows already-loaded objects to be used.

My proposal is to split pyramid_tm into 2 tweens that wrap the EXCVIEW. The OVER tween will perform the commit/abort while the UNDER tween will perform retries on normal views and mark state for later abort if exceptions are found. The transaction is kept alive until after the exception view has executed.

**Comment by mmerickel** [comment]
After discussing with @bertjwregeer and @dstufft I'm worried about changing this in the original way described.

The core issue here is that there is no valid transaction during exception views, `NewResponse`, or `request.add_finished_callback` callbacks. Even if the transaction is aborted later, it is still a big problem that there isn't one to be used at all. It leads to the following subtle bugs:

1) `DetachedInstanceErrors` if touching request properties populated during the normal request such as `request.user`. This property was cached, and now the session was closed by pyramid_tm before the exception view executes. So the ref is alive but pointing to a detached object.

2) Database sessions left open. If you perform a database query in an exception view *right now* another transaction is automatically opened but it is never closed. This is bad.

I'm struggling to come up with a good way to fix this in a way that is sane.

**Comment by davisagli** [comment]
What if we keep the transaction handling where it is currently, but also:
1. Add a way to designate request properties that should be cleaned up when a new transaction begins (i.e. a transaction data manager that undoes the work of `add_request_method` for specified properties).
2. Explicitly do a transaction abort following the exception view in case a new transaction was implicitly started.

This adds flexibility in how to approach goal 1, addresses goal 2, and keeps goal 3 working as it does now.

Thinking "aloud" so I'm probably overlooking some scenarios.

**Comment by mmerickel** [comment]
I was hoping for a more automated solution to expiring the variables but it just may not be possible. You could destroy all reified properties but that's too aggressive when you only want to hit properties that store managed state, not ones that store expensive computations.

Executing the exception view in a separate transaction is definitely not ideal, but it's an improvement over the current scenario. We could abort in a `request.add_finished_callback` such that anything happening after egress of pyramid_tm (including exception views) would be handled.

So far this looks like the best option.

`config.tm_reset_request_properties('user', ...)` ?

**Comment by mmerickel** [comment]
We could always expire everything by default and allow a whitelist approach. It is possible to expire reified properties automatically so long as they are registered using `add_request_method`.

**Comment by bertjwregeer** [comment]
The expire by default seems like a pretty good option. I don't store anything that is really that expensive to compute on my request object, and mostly just use reified to save myself one or two function calls.

However, in my exception views I don't tend to use database calls, so the only real reified thing that I have is my user object.

**Comment by lrowe** [comment]
@mmerickel asked me to chip in via email:

> The core of the issue is that there is currently a lot of undefined behavior around transaction boundaries when using pyramid_tm. The transactions could be lazily created by tweens prior to the pyramid_tm ingress, and people could easily be using the transactional data after the egress of pyramid_tm (in other tweens such as exception views, or even in response callbacks). Once the transaction is closed the next time someone touches a var a new transaction is lazily opened with no one to close it leaving dangling connections/resources.

> The list of features I'm interested in are:

> - Verify if ingress works properly with an already-active transaction.

Any existing transaction would be aborted when pyramid_tm calls ``manager.begin()``
 
> - Expand the transaction boundaries to encompass exception views and possibly response callbacks.

What to do for exceptions at transaction commit that are un-retryable or out-of-attempts? You may still need exception views for this.
 
> - Raise exception if a transaction is already active at ingress.

There is no public interface in transaction for this, but the check would be: ``assert manager._txn is None``. Another alternative would be to check that the transaction has no data managers: ``assert not txn._resources``. This really should use a public method.
 
> - Raise exception if a transaction is created after egress.

Not sure how to enforce this without changing transaction. You'd need a way to make TransactionManager.get() raise an error instead of implicitly creating a new transaction. I view the current behaviour of ``get()`` as a bit of a wart as unlike ``begin()``, it does not call ``newTransaction(txn)`` on any synchronizers. Fixing this would also fix the problem of unexpected new transactions at ingress.

--

The other pain point currently is that the request object is reused between attempts leading to ``DetachedInstanceErrors``. Most of the above problems are a direct result of using a tween rather than WSGI middleware. The only downside I can see to using *repoze.tm2* would be that you would need a way to register exception views for un-retryable / attempted-out exceptions during commit. Maybe we need to make that work instead. Or maybe subclass Router.

**Comment by mmerickel** [comment]
Your point about middleware is excellent. I hadn't really considered how many problems that solves by making a new request instance per transaction as well as wrapping the entire lifecycle. If that were the case then we would simply need to set something in the environ indicating the transaction should be not-retried or aborted upon exceptions.

Middleware does have the downside of not being handled by exception views, unfortunately and I'm afraid of reimplementing that horrific pylons error middleware which sent a new request into the system to generate an error view after catching exceptions on egress.

**Comment by mmerickel** [comment]
Fixed in #55.
