### ISSUE TITLE
request object is shared across retryable transaction attempts

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_tm#41]
This is really bad for any reified properties like `request.user` that are database objects. SQLAlchemy `DetachedInstanceErrors` abound.

The question is what to do about it? I'm thinking that pyramid_tm should inspect request extensions and just clear out everything that is reified upon errors, but maybe there is a better solution that is more general? We could make a new request object per transaction but I'm not really aware of the implications there... it seems possible though.

**Comment by bertjwregeer** [comment]
So long as you make the WSGI body seekable, it should be possible to have multiple request objects IIRC.

**Comment by tseaver** [comment]
Zope constructs a new request object (via `request.retry()`) when a retryable exception is raised.

**Comment by mmerickel** [comment]
@tseaver is there a way for us to do that here? My concern is that since pyramid_tm is a tween the request will have state that is lost from things like `NewRequest` subscribers if we create a new request object in the tween. There is definitely a delicate balance here between the benefits of middleware and tweens for this and I don't know what to do about it except that it's pretty broken right now.

**Comment by bertjwregeer** [comment]
@mmerickel Doesn't the request go back through the router upon a retry? Shouldn't NewRequest be sent to anyone listening again?

**Comment by mmerickel** [comment]
Okay I forgot that `NewRequest` is actually after tweens. I always forget that. I think creating a new request object is the right answer here. Especially in combination with what I want to do in https://github.com/Pylons/pyramid_tm/issues/40 these features will go hand in hand.

**Comment by mmerickel** [comment]
Fixed by #55 and the addition of the pyramid_retry package.
