### ISSUE TITLE
For no obvious reason pyramid_tm rolls back the transaction. 

### ISSUE THREAD

**Issue by bemineni** [Pylons/pyramid_tm#53]
I am using a recipe as suggested by Mike bayer https://bitbucket.org/zzzeek/sqlalchemy/wiki/UsageRecipes/SessionModifiedSQL. To  create and update sharded tables in the same database. His recipe works absolutely fine with sessions, when the same is added to a scoped session managed by pyramid_tm transactin manager, then it just rolls back the transaction at the end of request for no reason.

```
*view.py*

with session_shardid(DBSession,table_hash):	
			Base.metadata.create_all(DBSession.connection())
                        self.request.tm.commit()

*model.py*
DBSession = scoped_session(sessionmaker(extension=ZopeTransactionExtension()))

@listens_for(DBSession, "after_begin")
def _connection_for_session(session, trans, connection):
    """Share the 'info' dictionary of Session with Connection
    objects.
    This occurs as new Connection objects are associated with the
    Session.   The .info dictionary on Connection is local to the
    DBAPI connection.
    """
    connection.info['session_info'] = session.info

@contextmanager
def session_shardid(session, shardid):
    """Apply the "shard" id to all SQL emitted by the given Session.
    """
    session.info["shard"] = shardid
    yield
    del session.info["shard"]

@listens_for(Engine, "before_cursor_execute", retval=True)
def _apply_shard_id(connection, cursor, statement, parameters,
                                        context, executemany):
    """Apply a "shard id" to statements.

    Similar to the comment listener, we alter the statement on the
    fly replacing occurrences of "_shard_" with the current "shard id".

    """
    session_info = connection.info.get('session_info', {})
    if "shard" in session_info:
        statement = statement.replace("_shardid_", session_info["shard"])
        for param,value in parameters.items():
        	if isinstance(value, str):
        		parameters[param] = value.replace("_shardid_",session_info["shard"])

    return statement, parameters



2016-11-29 07:40:08,279 INFO  [sqlalchemy.engine.base.Engine:1145][b'uWSGIWorker2Core0'] {}
Inside _apply_shard_id
{'shard': 'ba6bd213'}
2016-11-29 07:40:08,298 INFO  [sqlalchemy.engine.base.Engine:1142][b'uWSGIWorker2Core0'] CREATE INDEX group_topic_ba6bd213_index1 ON group_topic_ba6bd213 (group_id, user_id)
2016-11-29 07:40:08,298 INFO  [sqlalchemy.engine.base.Engine:1145][b'uWSGIWorker2Core0'] {}
2016-11-29 07:40:08,300 INFO  [sqlalchemy.engine.base.Engine:701][b'uWSGIWorker2Core0'] ROLLBACK
[pid: 42827|app: 0|req: 1/1] 127.0.0.1 () {40 vars in 696 bytes} [Tue Nov 29 07:40:08 2016] GET /group_debug => generated 14 bytes in 99 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
```

The stack trace

````
Traceback (most recent call last):

  File "/home/izero/devel/medics_city/medics_city_env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/home/izero/devel/medics_city/medics_city_env/lib/python3.4/site-packages/sqlalchemy/pool.py", line 827, in _reset
    self._reset_agent.rollback()
  File "/home/izero/devel/medics_city/medics_city_env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1614, in rollback
    self._do_rollback()
  File "/home/izero/devel/medics_city/medics_city_env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1652, in _do_rollback
    self.connection._rollback_impl()
  File "/home/izero/devel/medics_city/medics_city_env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 694, in _rollback_impl
    tb = traceback.format_exc()

sqlalchemy/pool.py
def _rollback_impl(self):
        assert not self.__branch_from
        import traceback
        tb = traceback.format_exc()


        if self._has_events or self.engine._has_events:
            self.dispatch.rollback(self)


        **if self._still_open_and_connection_is_valid:**
            if self._echo:
                self.engine.logger.info("ROLLBACK")
            try:
                self.engine.dialect.do_rollback(self.connection)
            except BaseException as e:
                self._handle_dbapi_exception(e, None, None, None, None)
            finally:
                if not self.__invalid and \
                        self.connection._reset_agent is self.__transaction:
                    self.connection._reset_agent = None
                self.__transaction = None
        else:
            self.__transaction = None
```

**Comment by mmerickel** [comment]
The ZTE only tracks changes done by the ORM itself. If you are doing changes via `session.execute`, etc then the ZTE will not detect them. You need to use `zope.sqlalchemy.mark_changed(session)` to tell it that it changed. Alternatively you can initialize the ZTE into the `changed` state by default so it will always try to do a commit.

**Comment by bemineni** [comment]
1. 
   Base = declarative_base()
   Base.metadata.create_all(DBSession().connection()) -> **Is this considered outside ORM**
   This will always result in a roll back. 
   If I do zope.sqlalchemy.mark_changed(DBSession()), then it commits

   Base.metadata.create_all() -> succeeds

   what is  the difference between the two methods ?

   I need to connect the new connection with an event.
```
   @listens_for(DBSession, "after_begin")
   def _connection_for_session(session, trans, connection):
      """Share the 'info' dictionary of Session with Connection
      objects.
      This occurs as new Connection objects are associated with the
      Session.   The .info dictionary on Connection is local to the
      DBAPI connection.
      """
      connection.info['session_info'] = session.info
```

     For some reason connections initiated internally in the Engine, "contextual_connect" doesn't invoke the event 

2. How do we commit() a transaction in pyramid_tm. As per the documentation it says that the transaction manager is available at request.tm

Base = declarative_base()


Base.metadata.create_all(DBSession().connection())
request.tm.commit() doesn't commit any transaction ?

**Comment by mmerickel** [comment]
What is your metadata bound to? Presumably you ran `Base.metadata.bind = engine` somewhere with a raw engine object otherwise `create_all()` would not work with no arguments. An engine will not be managed by the ZTE.

Similarly, if you run `create_all` with a connection pulled from the session there's no reason to believe it would be managed by the ZTE either so `request.tm.commit()` doesn't do anything. This is because the connection itself inherits `autocommit=False` from the session and thus you must commit the connection directly (which never happens since you don't hold a reference to it). See http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.connection for information about that.

`request.tm.commit()` will invoke a commit if you are executing stuff on the **session that is joined to the transaction via the ZTE**. Anything else will not be managed by the ZTE / `request.tm`. From the docs linked above you may be able to start the transaction on the session, then grab the underlying connection. Since the transaction was started on session then the ZTE may manage it. Alternatively you could use the engine object directly via `create_all(DBSession().get_bind())` which should commit at the end.

**Comment by bemineni** [comment]
Sorry for the delay, was not able to work on this due to my job obligations. 


> Similarly, if you run create_all with a connection pulled from the session there's no reason to believe it would be managed by the ZTE either so request.tm.commit() doesn't do anything. This is because the connection itself inherits autocommit=False from the session and thus you must commit the connection directly (which never happens since you don't hold a reference to it). See http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.connection for information about that.

```
conn = DBSession().connection()
Base.metadata.create_all(conn) 
Here I have reference to the connection, how can I commit this.?
```

> request.tm.commit() will invoke a commit if you are executing stuff on the **session that is joined to the transaction via the ZTE.**

Can you please give some more info about what does this mean, why the below set of statements don't work. when everything is done using the session  and its established connection, which is managed by ZTE

From the last paragraph, this should work, but it comes back with an error that transaction has already been started, do you want to start a sub transaction. 

```
DBSession.begin()
Base.metadata.create_all(DBSession().connection()) 
request.tm.commit()
```

If the transaction is already started and I am pulling that sessions established connection, then why commit doesn't work on that connection.

```
Base.metadata.create_all(DBSession().connection()) 
request.tm.commit()
```

**Comment by bemineni** [comment]
I also want to start a new connection, because I need to connect it to an event. 

```
create_all(DBSession().get_bind())
OR
Base.metadata.bind = engine
Base.metadata.create_all()
```

The above methods never initiates the below event , when a connection is established.

```
DBSession = scoped_session(sessionmaker(extension=ZopeTransactionExtension()))
@listens_for(DBSession, "after_begin")
def _connection_for_session(session, trans, connection):
    """Share the 'info' dictionary of Session with Connection
    objects.
    This occurs as new Connection objects are associated with the
    Session.   The .info dictionary on Connection is local to the
    DBAPI connection.
    """
    connection.info['session_info'] = session.info
```

**Comment by bemineni** [comment]
Making the session dirty seems to be fixing the problem
