### ISSUE TITLE
Impossible to have a view handling commit time exception in 2.0

### ISSUE THREAD

**Issue by pvalsecc** [Pylons/pyramid_tm#62]
The default HTML generated by pyramid is not what I want. Up to version 1.1.1, I had no problem handling the commit time exceptions with a view declared like that:
```
@view_config(context=sqlalchemy.exc.IntegrityError, renderer="json", http_cache=0)
def integrity_error(exception, request):
    return _do_error(request, 400, exception)
```

But since pyramid_tm 2.0 as been moved `over=EXCVIEW` that view is not called anymore if I have a commit time error from the DB.

I've tried to add the `tm_active=True` view predicate, but that doesn't help.

**Comment by mmerickel** [comment]
@pvalsecc would you mind trying the changes in #61 and let me know if that helps. It is addressing this exact concern.

**Comment by pvalsecc** [comment]
Wow, that is fast!
Thanks, tested and it works. Now I just have to wait for a merge and a release.

**Comment by mmerickel** [comment]
Awesome, I'm glad I decided to implement this a mere 12 hours before you asked for it. It should go out sometime this week I just need another core dev to sign off on things first. Thanks for giving it a try!
