### ISSUE TITLE
Raising exception in a pre-commit hook doesn't abort the transaction

### ISSUE THREAD

**Issue by glasserc** [Pylons/pyramid_tm#63]
Since pyramid_tm 2.0, raising an exception in a pre-commit hook no longer marks the transaction as aborted. I've been trying to track down exactly what's going on, and I think there are two different things in 2.0 and 2.1. In 2.0, it seems like my transaction is getting retried somehow, and I'm not sure why. However, I'm more interested in porting to 2.1, so let's focus on that. It seems that as a result of https://github.com/Pylons/pyramid_tm/pull/61, the exception is caught and rendered. However, this does not cause the transaction to be aborted.

We were relying on the old behavior, where raising during pre-commit causes the transaction to abort, in Kinto. Our workaround (in https://github.com/Kinto/kinto/pull/1263) is to manually call `abort()` before we raise, but this seems a little strange. I'm hoping for advice on how to best accomplish our goals :)

Is it bad for us to even use a pre-commit hook in this way? Should we maybe be using a pre-commit veto or something instead? Personally, I feel that raising in a pre-commit should still abort the transaction. Another approach might be to abort the transaction in the `invoke_exception_view`, but we don't have any customizations of that so far and I don't know if now is the right time to add any.

Thanks for your time!

**Comment by mmerickel** [comment]
I implemented #61 under the assumption that `tm.commit()` would either work or end in an aborted transaction. This is apparently false. I suppose this means that I should add an explicit abort if it fails.

**Comment by mmerickel** [comment]
I was wondering how this was working before and it looks like the error raised by `tm.commit` would be caught by the exception handler and the transaction would be aborted again. This should be simple to handle but I must say it's quite unexpected to me that calling `tm.commit` could leave the transaction in such an odd state instead of aborting itself.

**Comment by tseaver** [comment]
In `transaction`, "Before commit" hooks are not actually allowed to raise (that is, the machinery does nothing to deal with any exceptions).

I would say this is a documentation issue for `transaction`, but wouldn't expect it to change.  Code which wants to be able to "vote" on a transaction should register a data manager with `tpc_vote`.

**Comment by mmerickel** [comment]
I'm happy rolling with that as well and marking this won't fix. What do you think @glasserc? I gotta say that trying to abort a commit in a beforeCommit hook that only executed because someone said commit sounds a little too late. If you want to defer some logic in your app about when to commit my recommendation would be to do it in a tween under the pyramid_tm one. If anything else raises it will be aborted anyway.

**Comment by mmerickel** [comment]
It is hard to propose another solution without seeing what you are relying on inside of the before commit hook. Definitely a commit veto  hook is a viable option but you also might be able to just raise an exception  earlier. Maybe I will find some time to look at what kinto is doing.

**Comment by glasserc** [comment]
For a little bit more information about what we're doing and why, Kinto is a database with a simple HTTP-based API that is designed to enable client-server synchronization. It's built to be extensible using plugins, with plugins being able to add endpoints or hook into various events (records being changed, for example). Some standard database features are implemented as plugins in Kinto, namely a "quotas" system preventing users from creating/updating records beyond a certain fixed storage limit. The quotas plugin is implemented by listening to a ResourceChanged event, and the listener to that event raises if the quota is exceeded. (The ResourceChanged event was fired in a beforeCommit hook, which was invoked by the pyramid_tm tween calling commit().)

I think I understand what you mean about trying to raise earlier. Let me try using the commit_veto hook and see if I can get it to work without too much sweat/tears, and if that doesn't work, maybe using a tween.

**Comment by glasserc** [comment]
Our interface with a plugin is that if a plugin raises an HTTP exception in response to a `ResourceChanged` event, we abort the transaction and we serve the exception as the response. It seems like if I raise during `commit_veto`, the response is discarded. (I could wrap the plugin's response in a `pyramid_tm.AbortWithResponse`, but I get the impression that this class is meant to be an internal implementation detail.)

**Comment by mmerickel** [comment]
Thanks for this info. A quick note is that I would expect the exception raised anywhere including a commit veto to be rendered through an exception view. These views have the option to, and will by default, return the original exception object in the case of the default HTTPException view registered in pyramid. Is this not what you're seeing?

**Comment by glasserc** [comment]
Actually, I'm not seeing that, which might be another interesting problem. I don't see any code that registers a program-wide exception view. When I raise, the exception gets dumped to console, but the client gets a generic 500 error response. Worse yet, during automated tests, calls like `self.app.post_json(...., status=500)` don't seem to get a 500, but rather the exception bubbles up through the application and into the test method. I'm not sure why we don't have an exception view, or if it's being registered somewhere else. Also, I noticed that pyramid_tm 2.1 registers its tween `over=EXCVIEW`, so does that mean only over an exception view?

I was also able to get something working using the default commit_veto hook and a tween that catches HTTPExceptions and returns them as responses. The use of tweens made me a little uneasy because the ordering is important -- it seems like it works OK if I use `over=tweens.EXCVIEW`, but really I need to be `under="pyramid_tm.tm_tween_factory"`, and tween ordering is "best effort", so I'm not sure what will happen if the `pyramid_tm` tween gets renamed.

**Comment by mmerickel** [comment]
I think I need to issue a retraction / apology and mention that all of my advice on this has been predicated on my in-the-weeds knowledge of new Pyramid 1.9 features. It is true that this will not work until Pyramid 1.9. In Pyramid < 1.9 exceptions above the EXCVIEW are not caught other than ones caused directly by commit/abort. You could replicate the upcoming features by adding a tween over pyramid_tm that catches exceptions and invokes `request.invoke_exception_view`.

**Comment by glasserc** [comment]
Actually, that information is very helpful. I read the code for the `pyramid` `EXCVIEW` and figured out that it was always being added (so you don't need to add it explicitly, at least in 1.8.4), and because `pyramid_tm` handles squashed exceptions without having to add `default_commit_veto`, I was able to put my new tween *under* the `EXCVIEW` and it does everything I want -- handling exceptions by rendering exception views and aborting transactions. I'm going to see what my co-worker thinks of my new solution. Thank you very much for your help (and the great software)!
