### ISSUE TITLE
SQLAlchemy ORM event 'deleted_to_detached' not called with pyramid_tm

### ISSUE THREAD

**Issue by cecemel** [Pylons/pyramid_tm#66]
Hello, 

I'am trying to listen to the SQLAlchemy ORM event [deleted_to_detached](http://docs.sqlalchemy.org/en/latest/orm/events.html#sqlalchemy.orm.events.SessionEvents.deleted_to_detached)
All work fine both directly under SQLAlchemy, as directly called trough Zope. But in a pyramid request context it does not work.

So far, all other events binding seem to work with pyramid_tm (as far as I tested them), but all events *_to_detached, do not seem to be called through pyramid_tm.

My educated guess there is some interference here with pyramid_tm, but if I am mistaken, please tell me. Also if you need more information, let me know.  

I'm using pyramid pyramid: 1.8.4, pyramid_tm: 2.1, zope.sqlalchemy: 0.7.7, SQLAlchemy: 1.1.13, Python 3.5

I included examples of what I'd like to achieve:
[SQLAlchemy version](https://gist.github.com/cecemel/1f7eaf52ec61d6572360177e80aa99c3)
[Zope version](https://gist.github.com/cecemel/91557a257d42f45fadbc30875c02657c)

If have time, I'll try to upload a pyramid example too.

thx

**Comment by mmerickel** [comment]
Certainly it would be helpful to see the pyramid example as that's the one you are having issues with. I'm pretty confident it's something to do with that example and not an issue with pyramid_tm. I'll leave this issue open for a little bit longer to give you a chance to upload an example but without it I'll have to close this.
