### ISSUE TITLE
Not compatible with transaction 2.4.0

### ISSUE THREAD

**Issue by glasserc** [Pylons/pyramid_tm#67]
`transaction` 2.4.0 came out today and it seems that it changes the structure of the `ThreadTransactionManager` in a way that `pyramid_tm` doesn't support. Our application's CI fails with errors like this:

```
Traceback (most recent call last):
  File "/home/travis/build/Kinto/kinto/.tox/py37/lib/python3.7/site-packages/pyramid_tm/__init__.py", line 149, in tm_tween
    maybe_tag_retryable(request, exc_info)
  File "/home/travis/build/Kinto/kinto/.tox/py37/lib/python3.7/site-packages/pyramid_tm/__init__.py", line 192, in maybe_tag_retryable
    if request.tm._retryable(*exc_info[:-1]):
AttributeError: 'ThreadTransactionManager' object has no attribute '_retryable'
```

**Comment by mmerickel** [comment]
@glasserc do you want to try out #68 before I merge and release?

**Comment by mmerickel** [comment]
I released 2.2.1.

**Comment by glasserc** [comment]
Thank you very much!

**Comment by Wim-De-Clercq** [comment]
Should the `2.2` release not be updated with a `transaction<2.4.0` requirement as well?

**Comment by bertjwregeer** [comment]
We can't update pins on older releases. PyPI won't allow us.

**Comment by mmerickel** [comment]
It's not standard practice to update old releases to deal with breakages in updates to dependencies. We just issue a new release that you can upgrade to when you choose to upgrade transaction. If you upgraded transaction but not pyramid_tm then there is an inconsistency in how you're pinning your dependencies.
