### ISSUE TITLE
Issue with "prepare for pyramid 2.0 by using authenticated_userid"

### ISSUE THREAD

**Issue by mardiros** [Pylons/pyramid_tm#73]
Hello,

I have an issue with the commit https://github.com/Pylons/pyramid_tm/commit/ac610d9db1a2ebfa90157162bac330686f9512ae which use the [authenticated_userid](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/interfaces.html#pyramid.interfaces.IAuthenticationPolicy.authenticated_userid) to log 
the [userid](https://docs.pylonsproject.org/projects/pyramid/en/master/glossary.html#term-userid)

we can read that in the doc:
`This method of the policy should ensure that a record exists in whatever persistent store`

But we are in the transaction manager here, so we are initializating the persistent store,
so the request.authenticated_userid access to uninitilized permistant data, doesn't it ?

Currently, my issue is that my implementation of `request.authenticated_userid` requires
that the `NewRequest` has been notified, but it is less critical I guess.

**Comment by mmerickel** [comment]
I'd recommend turning off the `tm.annotate_user` setting which should fix your issue.

In general, there is not a restriction that people can't access `request.authenticated_userid` in tweens, so I'd suggest thinking about how to avoid waiting for `NewRequest` in your implementation.
