### ISSUE TITLE
[2.4] accessing authenticated userid is breaking transaction boundaries

### ISSUE THREAD

**Issue by tdamsma** [Pylons/pyramid_tm#74]
I noticed that after upgrading to 2.4 my pyramid app keeps throwing sqlalchemy.orm.exc.DetachedInstanceError for the request.user object when accessing request.user in my view logic.

This is triggered by the change to the authenticated_userid annotating the user_id to the transaction. My authenticated user_id function looks like this:

```python
def authenticated_userid(self, request):
        user = request.user
        if user is not None:
            return str(user.id)
```

For the moment I can work with `tm.annotate_user=false`, but I wanted to report it anyway, perhaps I'm not the only one who runs into this. Probably related to https://github.com/Pylons/pyramid_tm/issues/13

**Comment by mmerickel** [comment]
I think I'll probably cut a release that just turns it off by default because I think it has very limited use. That being said, I'm not really sure why it'd be detached so early in the lifecycle - it smells like some mismanagement issue in your app but I can't speak to it in much more detail without seeing it.

**Comment by tdamsma** [comment]
Thanks for the reply, I'll try to dig into it deeper and turn it into a minimal shareable app; would be nice to know what I'm doing wrong that is causing this

**Comment by mmerickel** [comment]
Sure. A `DetachedInstanceError` means the user object is being shared across a commit/abort boundary. The `pyramid_tm` code is querying the `authenticated_userid` right after the transaction begins. So if you're seeing the error at that point it indicates that the user is cached from another transaction when there should really just be one transaction per request.

**Comment by tdamsma** [comment]
@mmerickel I reduced my problematic webapp down to [the minimum](https://gist.github.com/tdamsma/d514cf963cde37a234c4d85f6548aa84/59139fa0859a302bd75e2c2a45d8c43ef315254d). This app works as posted, but if you turn on `tm_annotate` it breaks. To try it out, just run the gist with python, visit localhost:6543 and refresh the page a few times.

This is to do with the way the request logging functionality I implemented, which calls transaction.commit() explicitly (required to get the changes to persist). But with you hints and this minimal example I think two of the three transaction.commit statements were necessary, and removing them allows the app to work in combination with `tm_annotate`. Still don't understand how the `tm_annotate` call breaks the first example, but I think removing the unnecessary  transaction.commit statements better anyway.

**Comment by mmerickel** [comment]
This gist is great, thank you for that. The basic problem here is you're just kind of not conforming to the world-view of pyramid_tm in which it expects to control the transaction. So you're doing all these explicit commits to track and update this logged_request object, regardless of what else happens during the request. This should be done using a separate transaction that isn't controlled by pyramid_tm.

You've made it pretty hard to reason about the lifecycles of some of the request objects like `request.user` which will not be accessible after a commit occurs, so in your current setup it's somewhat "random" based on various things whether request.user is accessed at the exact right time.

**Comment by tdamsma** [comment]
@mmerickel Thanks for looking at my gist. As is probably evident, my understanding of the transaction management is not as thorough is it probably should be. So your help is very much appreciated. I updated the request_logger bit as follows, does that make more sense? What I was trying to achieve is a simple way of logging and timing requests (including failed requests, and connected to user ids) from within the app (instead of setting this up in the webserver) as I want the result to be easily exposed in the admin interface, which I think is easier if the logs live in the same database as the rest of the app.

So I changed the request logging to use a separate transaction, not managed by pyramid_tm (see below or updated gist). Does this look better?

I am not so sure about the reify. They are there because I want to prevent repetitive calls to the request.user object to result in new database queries. 

```
def request_logger(event):
    request = event.request
    logged_request_t0 = time_ns()
    logged_request = LoggedRequest(request)
    logged_request.user_id = request.unauthenticated_userid

    session = request.registry["session_factory"](expire_on_commit=False)

    session.add(logged_request)
    session.commit()
    request.add_finished_callback(
        partial(
            request_finished_callback,
            session=session,
            logged_request=logged_request,
            logged_request_t0=logged_request_t0,
        )
    )
    request.add_response_callback(
        partial(response_callback, session=session, logged_request=logged_request)
    )


def request_finished_callback(
    request, session=None, logged_request=None, logged_request_t0=None
):
    logged_request.duration_ms = (time_ns() - logged_request_t0) / 1_000_000
    session.commit()


def response_callback(request, response, session=None, logged_request=None):
    logged_request.completed = True
    session.commit()
```

**Comment by mmerickel** [comment]
Yup that looks like a great approach - you'll want to call `session.close()` in the finished callback to release the connection aggressively back to the pool. It's good to get that stuff out of the primary transaction and leave it focused on the actual user-level data that should be committed or aborted wholesale.
